//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbilightController.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LedCountTop {
            get {
                return ((int)(this["LedCountTop"]));
            }
            set {
                this["LedCountTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int LedCountRight {
            get {
                return ((int)(this["LedCountRight"]));
            }
            set {
                this["LedCountRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int LedCountBottom {
            get {
                return ((int)(this["LedCountBottom"]));
            }
            set {
                this["LedCountBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int LedCountLeft {
            get {
                return ((int)(this["LedCountLeft"]));
            }
            set {
                this["LedCountLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float LedBrightness {
            get {
                return ((float)(this["LedBrightness"]));
            }
            set {
                this["LedBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LedFirstIndex {
            get {
                return ((int)(this["LedFirstIndex"]));
            }
            set {
                this["LedFirstIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LedClockwise {
            get {
                return ((bool)(this["LedClockwise"]));
            }
            set {
                this["LedClockwise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LedDeviceCOM {
            get {
                return ((string)(this["LedDeviceCOM"]));
            }
            set {
                this["LedDeviceCOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LedMode {
            get {
                return ((int)(this["LedMode"]));
            }
            set {
                this["LedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ModeScreenPointPerLed {
            get {
                return ((int)(this["ModeScreenPointPerLed"]));
            }
            set {
                this["ModeScreenPointPerLed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ModeScreenOffset {
            get {
                return ((int)(this["ModeScreenOffset"]));
            }
            set {
                this["ModeScreenOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ModeScreenPointSpacing {
            get {
                return ((int)(this["ModeScreenPointSpacing"]));
            }
            set {
                this["ModeScreenPointSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModeScreen60Fps {
            get {
                return ((bool)(this["ModeScreen60Fps"]));
            }
            set {
                this["ModeScreen60Fps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModeScreenToCenter {
            get {
                return ((bool)(this["ModeScreenToCenter"]));
            }
            set {
                this["ModeScreenToCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModeRainbowClockwise {
            get {
                return ((bool)(this["ModeRainbowClockwise"]));
            }
            set {
                this["ModeRainbowClockwise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float ModeRainbowSpeed {
            get {
                return ((float)(this["ModeRainbowSpeed"]));
            }
            set {
                this["ModeRainbowSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ModeRainbowRepeats {
            get {
                return ((int)(this["ModeRainbowRepeats"]));
            }
            set {
                this["ModeRainbowRepeats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ModePulseColor {
            get {
                return ((global::System.Drawing.Color)(this["ModePulseColor"]));
            }
            set {
                this["ModePulseColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float ModePulseSpeed {
            get {
                return ((float)(this["ModePulseSpeed"]));
            }
            set {
                this["ModePulseSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ModePulseMinBrightness {
            get {
                return ((float)(this["ModePulseMinBrightness"]));
            }
            set {
                this["ModePulseMinBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float ModePulseMaxBrightness {
            get {
                return ((float)(this["ModePulseMaxBrightness"]));
            }
            set {
                this["ModePulseMaxBrightness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ModeSparkleSpeed {
            get {
                return ((int)(this["ModeSparkleSpeed"]));
            }
            set {
                this["ModeSparkleSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ModeSparkleAmount {
            get {
                return ((int)(this["ModeSparkleAmount"]));
            }
            set {
                this["ModeSparkleAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ModeSparkleColor {
            get {
                return ((global::System.Drawing.Color)(this["ModeSparkleColor"]));
            }
            set {
                this["ModeSparkleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color ModeSparkleColorRare {
            get {
                return ((global::System.Drawing.Color)(this["ModeSparkleColorRare"]));
            }
            set {
                this["ModeSparkleColorRare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ModeFixedColor {
            get {
                return ((global::System.Drawing.Color)(this["ModeFixedColor"]));
            }
            set {
                this["ModeFixedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ModeMouseXColor {
            get {
                return ((global::System.Drawing.Color)(this["ModeMouseXColor"]));
            }
            set {
                this["ModeMouseXColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ModeMouseYColor {
            get {
                return ((global::System.Drawing.Color)(this["ModeMouseYColor"]));
            }
            set {
                this["ModeMouseYColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float ModeMouseTrailLength {
            get {
                return ((float)(this["ModeMouseTrailLength"]));
            }
            set {
                this["ModeMouseTrailLength"] = value;
            }
        }
    }
}
